name: Api Unit

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install
        run: |-
          cd api
          yarn install

      - name: Test
        run: |-
          cd api
          yarn jest --forceExit --coverage --ci
        env:
          SECRET_KNEX_CONNECTION: postgres://postgres:postgres@localhost:5432/testing
