name: Www Unit

on:
  workflow_dispatch:
  push:
    paths:
      - 'www/**'
  pull_request:
    paths:
      - 'www/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: www/package-lock.json
      - name: Install
        run: |
          npm install -g npm@latest
          cd www
          npm install
      - name: Test
        run: |-
          cd www
          npm exec jest -- --forceExit --coverage --ci
