name: Www Unit

on:
  workflow_dispatch:
  push:
    paths:
      - 'www/**'
  pull_request:
    paths:
      - 'www/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - name: Test
        run: |-
          npm run ci:www
